// @ts-nocheck
// Fresh-generation isolation critique (#1043).
//
// These fixtures drive the production comping engine through the two detached
// export hosts. Only the audio sink is mocked: MIDI events and WAV buffer notes
// are generated by the real tick path. Deliberately dirtying every comp-memory
// field between identical runs must not change their symbolic onset traces.
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { compingState } from '../../public/engine/accompaniment.js';
import { validateProgression } from '../../public/engine/chords-engine.js';
import { ExportProcessor } from '../../public/engine/midi-worker-logic.js';
import { renderCurrentSessionToWav, renderStemsToWav } from '../../public/export/audio-export.js';
import { dispatch, getState } from '../../public/state.js';
import { ACTIONS } from '../../public/types.js';

const { initAudioMock, scheduleGlobalEventMock } = vi.hoisted(() => ({
    initAudioMock: vi.fn(),
    scheduleGlobalEventMock: vi.fn(),
}));

vi.mock('../../public/engine/engine.js', () => ({
    initAudio: initAudioMock,
}));
vi.mock('../../public/engine/scheduler-core.js', () => ({
    scheduleGlobalEvent: scheduleGlobalEventMock,
}));

function buildFunkState() {
    dispatch(ACTIONS.RESET_STATE);
    dispatch(ACTIONS.SET_KEY, 'C');
    dispatch(ACTIONS.UPDATE_GB, { enabled: true, genreFeel: 'Funk' });
    dispatch(ACTIONS.SET_BAND_INTENSITY, 0.68);
    dispatch(ACTIONS.SET_BPM, 104);

    const state = getState();
    state.arranger.sections = [
        {
            id: 'funk-a',
            label: 'Funk Vamp',
            value: 'C9 | C9 | F9 | G9',
            key: 'C',
            timeSignature: '4/4',
        },
    ];
    state.arranger.key = 'C';
    state.arranger.isMinor = false;
    state.arranger.timeSignature = '4/4';
    state.arranger.seed = 'generation-run-isolation';
    state.playback.complexity = 0.5;
    state.chords.enabled = true;
    state.chords.style = 'smart';
    state.bass.enabled = false;
    state.soloist.enabled = false;
    state.harmony.enabled = false;
    validateProgression(state);
    return state;
}

function dirtyCompingMemory(sectionId = 'funk-a') {
    Object.assign(compingState, {
        currentVibe: 'active',
        currentCell: new Array(16).fill(1),
        lockedUntil: 999,
        soloistActivity: 1,
        lastChordIndex: 7,
        lastChordQuality: '7alt',
        grooveRetentionCount: 3,
        maxGrooveLength: 8,
        lastSectionId: sectionId,
        lastVoicingMidis: [60, 64, 67],
        statementVoicingMidis: [60, 64, 67, 70],
        statementChordKey: '60:7',
        ringSuppressStep: 14,
        ringSuppressChordKey: '60:7',
        funkRotationIndex: 7,
        bossaRotationIndex: 6,
    });
}

function makeFakeOfflineAudioContext() {
    return vi.fn(function FakeOAC(
        this: any,
        numberOfChannels: number,
        length: number,
        sampleRate: number,
    ) {
        this.startRendering = vi.fn(async () => ({
            numberOfChannels,
            sampleRate,
            duration: length / sampleRate,
            getChannelData: () => new Float32Array(length),
        }));
    });
}

function renderMidiChordTrace() {
    const state = buildFunkState();
    const processor = new ExportProcessor(state, {
        includedTracks: ['chords'],
        loopMode: 'once',
    });
    const trace = [];
    for (let step = 0; step < state.arranger.totalSteps; step++) {
        const before = processor.chordTrack.events.length;
        processor.processStep(step);
        const midis = processor.chordTrack.events
            .slice(before)
            .filter((event) => (event.data[0] & 0xf0) === 0x90)
            .map((event) => event.data[1]);
        trace.push({ step, midis });
    }
    processor.cleanup();
    return trace;
}

describe('fresh generation-run isolation (#1043)', () => {
    beforeEach(() => {
        vi.clearAllMocks();
        vi.stubGlobal('postMessage', vi.fn());
        vi.stubGlobal('OfflineAudioContext', makeFakeOfflineAudioContext());
        vi.spyOn(Math, 'random').mockReturnValue(0.5);
    });

    afterEach(() => {
        vi.restoreAllMocks();
        vi.unstubAllGlobals();
    });

    it('gives MIDI the same production chord trace after dirty hidden memory', () => {
        const first = renderMidiChordTrace();
        dirtyCompingMemory();
        const second = renderMidiChordTrace();

        expect(first.some(({ midis }) => midis.length > 0)).toBe(true);
        expect(second).toEqual(first);
    });

    it('gives full WAV and sequential stems the same two-loop production trace', async () => {
        const traces = [];
        initAudioMock.mockImplementation(() => traces.push([]));
        scheduleGlobalEventMock.mockImplementation((state, step) => {
            const midis = (state.chords.buffer.get(step) || [])
                .filter((note) => note.midi > 0 && note.muted !== true)
                .map((note) => note.midi);
            traces.at(-1).push({ step, midis });
        });
        buildFunkState();

        await renderCurrentSessionToWav({ loops: 2, sampleRate: 100 });
        dirtyCompingMemory();
        await renderStemsToWav(['chords', 'chords'], { loops: 2, sampleRate: 100 });

        expect(traces).toHaveLength(3);
        expect(traces[0].some(({ midis }) => midis.length > 0)).toBe(true);
        expect(traces[1]).toEqual(traces[0]);
        expect(traces[2]).toEqual(traces[0]);
    });
});
