import type { EnsembleState } from '../types.js';

export type PersistenceOwner = 'document' | 'preferences' | 'runtime-derived';

type SliceOwnership<T> = { readonly [K in keyof T]-?: PersistenceOwner };

type StateOwnershipManifest = {
    readonly [Slice in keyof EnsembleState]-?: SliceOwnership<EnsembleState[Slice]>;
};

/**
 * Exhaustive ownership at the live slice boundary. `satisfies` is the guard: a
 * new top-level state field fails typecheck until it is deliberately classified.
 * Nested runtime aggregates (`soloist.session`, audio graphs, buffers) stay one
 * runtime-owned unit because no codec may project their internals.
 */
export const STATE_OWNERSHIP_MANIFEST = {
    arranger: {
        scorePlan: 'runtime-derived',
        sections: 'document',
        progression: 'runtime-derived',
        key: 'document',
        timeSignature: 'document',
        isMinor: 'document',
        notation: 'document',
        valid: 'runtime-derived',
        totalSteps: 'runtime-derived',
        stepMap: 'runtime-derived',
        measureMap: 'runtime-derived',
        sectionMap: 'runtime-derived',
        history: 'runtime-derived',
        lastInteractedSectionId: 'runtime-derived',
        mutatedSectionId: 'runtime-derived',
        isDirty: 'runtime-derived',
        grouping: 'document',
        seed: 'document',
        randomizeSeed: 'document',
    },
    playback: {
        audio: 'runtime-derived',
        audioGraph: 'runtime-derived',
        isPlaying: 'runtime-derived',
        bpm: 'document',
        nextNoteTime: 'runtime-derived',
        unswungNextNoteTime: 'runtime-derived',
        scheduleAheadTime: 'runtime-derived',
        step: 'runtime-derived',
        currentSectionId: 'runtime-derived',
        startStep: 'runtime-derived',
        loopStartStep: 'runtime-derived',
        loopEndStep: 'runtime-derived',
        drawQueue: 'runtime-derived',
        isCountingIn: 'runtime-derived',
        countInBeat: 'runtime-derived',
        isDrawing: 'runtime-derived',
        palette: 'preferences',
        mode: 'preferences',
        wakeLock: 'runtime-derived',
        // The chart's energy (`ChartPerformance.energy`, DECISION 2026-09-26): the user is
        // the only writer; nothing at runtime modulates it.
        bandIntensity: 'document',
        motifBarIntensity: 'runtime-derived',
        autoIntensity: 'document',
        metronome: 'runtime-derived',
        applyPresetSettings: 'preferences',
        sustainActive: 'runtime-derived',
        songMode: 'preferences',
        sessionTimer: 'preferences',
        debugSoloist: 'runtime-derived',
        sessionStartTime: 'runtime-derived',
        isEndingPending: 'runtime-derived',
        intent: 'runtime-derived',
        lastActiveDrumElements: 'runtime-derived',
        heldNotes: 'runtime-derived',
        activeChordVoices: 'runtime-derived',
        lastChordKey: 'runtime-derived',
        lastPlayingStep: 'runtime-derived',
        workerLogging: 'runtime-derived',
        suspendTimeout: 'runtime-derived',
        currentKey: 'runtime-derived',
        conductorVelocity: 'runtime-derived',
        // #1064 — runtime-derived mirror composed at read time with harmony.complexity;
        // never written onto that document-owned field directly.
        conductorHarmonyComplexity: 'runtime-derived',
        masterVolume: 'preferences',
        countIn: 'preferences',
        visualFlash: 'preferences',
        qualityColors: 'preferences',
        toasts: 'runtime-derived',
        flashIntensity: 'runtime-derived',
        resolutionTriggered: 'runtime-derived',
        isScheduling: 'runtime-derived',
        modals: 'runtime-derived',
        loopLimit: 'runtime-derived',
        currentLoopCount: 'runtime-derived',
        chartLocked: 'runtime-derived',
    },
    groove: {
        enabled: 'document',
        voice: 'document',
        autoSound: 'document',
        volume: 'document',
        reverb: 'document',
        humanize: 'document',
        swing: 'document',
        swingSub: 'document',
        seed: 'runtime-derived',
        audioBuffers: 'runtime-derived',
        genreFeel: 'document',
        fillActive: 'runtime-derived',
        fillSteps: 'runtime-derived',
        lastHatGain: 'runtime-derived',
        lastSampledHatVoice: 'runtime-derived',
        lastRideGain: 'runtime-derived',
        lastCrashGain: 'runtime-derived',
        fillStartStep: 'runtime-derived',
        fillLength: 'runtime-derived',
        snareMask: 'runtime-derived',
        pendingCrash: 'runtime-derived',
        sectionSeedMap: 'runtime-derived',
        lastSmartGenre: 'document',
        pendingGenreFeel: 'runtime-derived',
        genreSwitchCountdown: 'runtime-derived',
        orchestrationMap: 'runtime-derived',
        fillMap: 'runtime-derived',
        accentMap: 'runtime-derived',
        seedTimelineStartStep: 'runtime-derived',
        variations: 'runtime-derived',
        buffer: 'runtime-derived',
    },
    chords: {
        enabled: 'document',
        voice: 'document',
        autoSound: 'document',
        style: 'document',
        volume: 'document',
        reverb: 'document',
        lastActiveChordIndex: 'runtime-derived',
        scheduledChordIndex: 'runtime-derived',
        buffer: 'runtime-derived',
        rhythmicMask: 'runtime-derived',
    },
    bass: {
        enabled: 'document',
        voice: 'document',
        autoSound: 'document',
        volume: 'document',
        reverb: 'document',
        lastFreq: 'runtime-derived',
        lastPlayedFreq: 'runtime-derived',
        buffer: 'runtime-derived',
        style: 'document',
        busySteps: 'runtime-derived',
        lastMidiPlayed: 'runtime-derived',
        lastBassGain: 'runtime-derived',
    },
    soloist: {
        enabled: 'document',
        voice: 'document',
        autoSound: 'document',
        mode: 'document',
        autoMode: 'document',
        style: 'document',
        volume: 'document',
        reverb: 'document',
        tradeWith: 'document',
        tradeBars: 'document',
        tradeChoruses: 'document',
        session: 'runtime-derived',
        audio: 'runtime-derived',
    },
    harmony: {
        enabled: 'document',
        voice: 'document',
        autoSound: 'document',
        volume: 'document',
        reverb: 'document',
        buffer: 'runtime-derived',
        octave: 'document',
        style: 'document',
        complexity: 'document',
        motifBuffer: 'runtime-derived',
        rhythmicMask: 'runtime-derived',
        lastMidis: 'runtime-derived',
        activeVoices: 'runtime-derived',
    },
    midi: {
        enabled: 'preferences',
        outputs: 'runtime-derived',
        selectedOutputId: 'preferences',
        chordsChannel: 'preferences',
        bassChannel: 'preferences',
        soloistChannel: 'preferences',
        harmonyChannel: 'preferences',
        drumsChannel: 'preferences',
        latency: 'preferences',
        muteLocal: 'preferences',
        chordsOctave: 'preferences',
        bassOctave: 'preferences',
        soloistOctave: 'preferences',
        harmonyOctave: 'preferences',
        drumsOctave: 'preferences',
        velocitySensitivity: 'preferences',
        inputs: 'runtime-derived',
        selectedInputId: 'preferences',
        inputEnabled: 'preferences',
    },
    vizState: {
        enabled: 'preferences',
    },
    conductor: {
        targetIntensity: 'runtime-derived',
        stepSize: 'runtime-derived',
        form: 'runtime-derived',
        formIteration: 'runtime-derived',
    },
} as const satisfies StateOwnershipManifest;
