import type { EnsembleState } from '../types.js';

export type PersistenceOwner = 'document' | 'preferences' | 'runtime-derived';

type SliceOwnership<T> = { readonly [K in keyof T]-?: PersistenceOwner };

type StateOwnershipManifest = {
    readonly [Slice in keyof EnsembleState]-?: SliceOwnership<EnsembleState[Slice]>;
};

/**
 * Exhaustive ownership at the live slice boundary. `satisfies` is the guard: a
 * new top-level state field fails typecheck until it is deliberately classified.
 * Nested runtime aggregates (`soloist.session`, audio graphs, buffers) stay one
 * runtime-owned unit because no codec may project their internals.
 */
export const STATE_OWNERSHIP_MANIFEST = {
    arranger: {
        sections: 'document',
        progression: 'runtime-derived',
        key: 'document',
        timeSignature: 'document',
        isMinor: 'document',
        notation: 'document',
        valid: 'runtime-derived',
        totalSteps: 'runtime-derived',
        stepMap: 'runtime-derived',
        measureMap: 'runtime-derived',
        sectionMap: 'runtime-derived',
        history: 'runtime-derived',
        lastInteractedSectionId: 'runtime-derived',
        lastChordPreset: 'document',
        mutatedSectionId: 'runtime-derived',
        isDirty: 'runtime-derived',
        grouping: 'document',
        seed: 'document',
        randomizeSeed: 'document',
    },
    playback: {
        audio: 'runtime-derived',
        audioGraph: 'runtime-derived',
        isPlaying: 'runtime-derived',
        bpm: 'document',
        nextNoteTime: 'runtime-derived',
        unswungNextNoteTime: 'runtime-derived',
        scheduleAheadTime: 'runtime-derived',
        step: 'runtime-derived',
        currentSectionId: 'runtime-derived',
        startStep: 'runtime-derived',
        loopStartStep: 'runtime-derived',
        loopEndStep: 'runtime-derived',
        rampBpm: 'runtime-derived',
        rampBpmPerLoop: 'preferences',
        rampStartPct: 'preferences',
        rampBpmTarget: 'runtime-derived',
        drawQueue: 'runtime-derived',
        isCountingIn: 'runtime-derived',
        countInBeat: 'runtime-derived',
        isDrawing: 'runtime-derived',
        palette: 'preferences',
        mode: 'preferences',
        wakeLock: 'runtime-derived',
        bandIntensity: 'runtime-derived',
        motifBarIntensity: 'runtime-derived',
        complexity: 'document',
        autoIntensity: 'runtime-derived',
        practiceMode: 'preferences',
        metronome: 'runtime-derived',
        applyPresetSettings: 'preferences',
        sustainActive: 'runtime-derived',
        songMode: 'preferences',
        sessionTimer: 'preferences',
        debugSoloist: 'runtime-derived',
        sessionStartTime: 'runtime-derived',
        isEndingPending: 'runtime-derived',
        intent: 'runtime-derived',
        lastActiveDrumElements: 'runtime-derived',
        heldNotes: 'runtime-derived',
        activeChordVoices: 'runtime-derived',
        lastChordKey: 'runtime-derived',
        lastPlayingStep: 'runtime-derived',
        workerLogging: 'runtime-derived',
        suspendTimeout: 'runtime-derived',
        currentKey: 'runtime-derived',
        conductorVelocity: 'runtime-derived',
        masterVolume: 'preferences',
        countIn: 'preferences',
        visualFlash: 'preferences',
        qualityColors: 'preferences',
        toasts: 'runtime-derived',
        flashIntensity: 'runtime-derived',
        updateAvailable: 'runtime-derived',
        resolutionTriggered: 'runtime-derived',
        isScheduling: 'runtime-derived',
        modals: 'runtime-derived',
        settingsTab: 'runtime-derived',
        loopLimit: 'runtime-derived',
        currentLoopCount: 'runtime-derived',
        chartLocked: 'runtime-derived',
    },
    groove: {
        enabled: 'document',
        voice: 'document',
        autoSound: 'document',
        instruments: 'document',
        volume: 'document',
        reverb: 'document',
        measures: 'document',
        currentMeasure: 'runtime-derived',
        humanize: 'document',
        swing: 'document',
        swingSub: 'document',
        lastDrumPreset: 'document',
        seed: 'runtime-derived',
        audioBuffers: 'runtime-derived',
        genreFeel: 'document',
        fillActive: 'runtime-derived',
        fillSteps: 'runtime-derived',
        lastHatGain: 'runtime-derived',
        lastSampledHatVoice: 'runtime-derived',
        lastRideGain: 'runtime-derived',
        lastCrashGain: 'runtime-derived',
        fillStartStep: 'runtime-derived',
        fillLength: 'runtime-derived',
        snareMask: 'runtime-derived',
        pendingCrash: 'runtime-derived',
        sectionSeedMap: 'runtime-derived',
        lastSmartGenre: 'document',
        pendingGenreFeel: 'runtime-derived',
        genreSwitchCountdown: 'runtime-derived',
        orchestrationMap: 'runtime-derived',
        fillMap: 'runtime-derived',
        accentMap: 'runtime-derived',
        seedTimelineStartStep: 'runtime-derived',
        variations: 'runtime-derived',
        buffer: 'runtime-derived',
    },
    chords: {
        enabled: 'document',
        voice: 'document',
        autoSound: 'document',
        style: 'document',
        volume: 'document',
        reverb: 'document',
        octave: 'document',
        density: 'document',
        lastActiveChordIndex: 'runtime-derived',
        scheduledChordIndex: 'runtime-derived',
        buffer: 'runtime-derived',
        rhythmicMask: 'runtime-derived',
        instrument: 'document',
    },
    bass: {
        enabled: 'document',
        voice: 'document',
        autoSound: 'document',
        volume: 'document',
        reverb: 'document',
        lastFreq: 'runtime-derived',
        lastPlayedFreq: 'runtime-derived',
        buffer: 'runtime-derived',
        octave: 'document',
        style: 'document',
        busySteps: 'runtime-derived',
        lastMidiPlayed: 'runtime-derived',
        lastBassGain: 'runtime-derived',
    },
    soloist: {
        enabled: 'document',
        voice: 'document',
        autoSound: 'document',
        preset: 'document',
        mode: 'document',
        autoMode: 'document',
        style: 'document',
        octave: 'document',
        volume: 'document',
        reverb: 'document',
        complexity: 'runtime-derived',
        phrasingIntensity: 'document',
        tradeMode: 'document',
        session: 'runtime-derived',
        audio: 'runtime-derived',
    },
    harmony: {
        enabled: 'document',
        voice: 'document',
        autoSound: 'document',
        volume: 'document',
        reverb: 'document',
        buffer: 'runtime-derived',
        octave: 'document',
        style: 'document',
        complexity: 'document',
        motifBuffer: 'runtime-derived',
        rhythmicMask: 'runtime-derived',
        lastMidis: 'runtime-derived',
        activeVoices: 'runtime-derived',
    },
    midi: {
        enabled: 'preferences',
        outputs: 'runtime-derived',
        selectedOutputId: 'preferences',
        chordsChannel: 'preferences',
        bassChannel: 'preferences',
        soloistChannel: 'preferences',
        harmonyChannel: 'preferences',
        drumsChannel: 'preferences',
        latency: 'preferences',
        muteLocal: 'preferences',
        chordsOctave: 'preferences',
        bassOctave: 'preferences',
        soloistOctave: 'preferences',
        harmonyOctave: 'preferences',
        drumsOctave: 'preferences',
        velocitySensitivity: 'preferences',
        inputs: 'runtime-derived',
        selectedInputId: 'preferences',
        inputEnabled: 'preferences',
    },
    vizState: {
        enabled: 'preferences',
    },
    conductor: {
        targetIntensity: 'runtime-derived',
        stepSize: 'runtime-derived',
        form: 'runtime-derived',
        formIteration: 'runtime-derived',
    },
} as const satisfies StateOwnershipManifest;

/**
 * The legacy writer remains intentionally unchanged. This nested-path view is
 * compared behaviorally with its emitted payload in tests, so adding or removing
 * a legacy field forces an ownership decision without making the new codecs
 * depend on the old storage shape.
 */
export const LEGACY_PERSISTED_FIELD_OWNERSHIP = {
    sections: 'document',
    key: 'document',
    timeSignature: 'document',
    grouping: 'document',
    isMinor: 'document',
    notation: 'document',
    lastChordPreset: 'document',
    seed: 'document',
    randomizeSeed: 'document',
    palette: 'preferences',
    mode: 'preferences',
    bpm: 'document',
    complexity: 'document',
    metronome: 'runtime-derived',
    visualFlash: 'preferences',
    qualityColors: 'preferences',
    countIn: 'preferences',
    applyPresetSettings: 'preferences',
    sessionTimer: 'preferences',
    songMode: 'preferences',
    vizEnabled: 'preferences',
    autoIntensity: 'runtime-derived',
    practiceMode: 'preferences',
    masterVolume: 'preferences',
    mixerVersion: 'runtime-derived',
    'chords.enabled': 'document',
    'chords.voice': 'document',
    'chords.autoSound': 'document',
    'chords.style': 'document',
    'chords.instrument': 'document',
    'chords.octave': 'document',
    'chords.density': 'document',
    'chords.volume': 'document',
    'chords.reverb': 'document',
    'bass.enabled': 'document',
    'bass.voice': 'document',
    'bass.autoSound': 'document',
    'bass.style': 'document',
    'bass.octave': 'document',
    'bass.volume': 'document',
    'bass.reverb': 'document',
    'soloist.enabled': 'document',
    'soloist.voice': 'document',
    'soloist.autoSound': 'document',
    'soloist.style': 'document',
    'soloist.preset': 'document',
    'soloist.octave': 'document',
    'soloist.volume': 'document',
    'soloist.reverb': 'document',
    'soloist.mode': 'document',
    'soloist.autoMode': 'document',
    'soloist.phrasingIntensity': 'document',
    'harmony.enabled': 'document',
    'harmony.voice': 'document',
    'harmony.autoSound': 'document',
    'harmony.style': 'document',
    'harmony.octave': 'document',
    'harmony.volume': 'document',
    'harmony.reverb': 'document',
    'harmony.complexity': 'document',
    'groove.enabled': 'document',
    'groove.voice': 'document',
    'groove.autoSound': 'document',
    'groove.volume': 'document',
    'groove.reverb': 'document',
    'groove.swing': 'document',
    'groove.swingSub': 'document',
    'groove.humanize': 'document',
    'groove.lastDrumPreset': 'document',
    'groove.genreFeel': 'document',
    'groove.lastSmartGenre': 'document',
    'groove.sectionSeedMap': 'runtime-derived',
    'groove.pattern': 'document',
    'midi.enabled': 'preferences',
    'midi.selectedOutputId': 'preferences',
    'midi.inputEnabled': 'preferences',
    'midi.selectedInputId': 'preferences',
    'midi.chordsChannel': 'preferences',
    'midi.bassChannel': 'preferences',
    'midi.soloistChannel': 'preferences',
    'midi.harmonyChannel': 'preferences',
    'midi.drumsChannel': 'preferences',
    'midi.chordsOctave': 'preferences',
    'midi.bassOctave': 'preferences',
    'midi.soloistOctave': 'preferences',
    'midi.harmonyOctave': 'preferences',
    'midi.drumsOctave': 'preferences',
    'midi.latency': 'preferences',
    'midi.muteLocal': 'preferences',
    'midi.velocitySensitivity': 'preferences',
} as const satisfies Record<string, PersistenceOwner>;
