// Parity with the HTML prototype (reference/shell-voicings.html).
// golden.json was generated by running the prototype's own voicer in a headless DOM across
// song shapes, keys, hand windows and root-string limits. The TypeScript engine must match it note for note.
import { readFileSync } from 'node:fs';
import { describe, expect, it } from 'vitest';
import { GUITAR, UKULELE, voiceChart } from '../index';
import { keyRoot, SONG_SHAPES, songChart } from './keys';

interface GoldenCase {
    ins: 'guitar' | 'uke';
    rootSet: 'all' | 'classic';
    win: number | null;
    song: string;
    key: string;
    mode: string;
    chords: Array<{
        sym: string;
        shape: string;
        r: number;
        notes: Array<[number, number, string, string, number | null]>;
    }>;
}
const file = process.env.GOLDEN ?? new URL('./golden.json', import.meta.url);
const cases: GoldenCase[] = JSON.parse(readFileSync(file, 'utf8'));

describe('voiceChart matches the prototype', () => {
    it(`covers ${cases.length} charts`, () => expect(cases.length).toBeGreaterThan(0));
    for (const c of cases) {
        const label = `${c.ins} ${c.rootSet} win=${c.win ?? 'any'} ${c.song} in ${c.key}`;
        it(label, () => {
            const instrument = c.ins === 'guitar' ? GUITAR : UKULELE;
            const chart = songChart(keyRoot(c.key), SONG_SHAPES[c.song]);
            const voiced = voiceChart(chart, {
                instrument,
                home: c.win === null ? null : [c.win, c.win + 5],
                rootStrings: c.ins === 'guitar' && c.rootSet === 'classic' ? [6, 5] : undefined,
            });
            const got = voiced.map((v) => ({
                sym: v.symbol,
                shape: v.shape.id,
                r: v.rootFret,
                notes: v.notes.map((n) => [n.string, n.fret, n.degree, n.role, n.finger]),
            }));
            expect(got).toEqual(c.chords);
        });
    }
});
