/** Maps drum instrument names to standard MIDI drum notes (General MIDI). */
export const DRUM_MAP: Record<string, number> = {
    Kick: 36,
    Snare: 38,
    HiHat: 42,
    Open: 46,
    Crash: 49,
    Ride: 51,
    Rim: 37,
    Clap: 39,
    Cowbell: 56,
    Shaker: 70,
    Clave: 75,
    Conga: 63,
    Bongo: 60,
    Perc: 67,
    Guiro: 74,
    'High Tom': 50,
    'Mid Tom': 47,
    'Low Tom': 43,
    Sidestick: 37,
    Agogo: 67,
    'High Agogo': 67,
    'Low Agogo': 68,
    'High Bongo': 60,
    'Low Bongo': 61,
    'High Conga': 62,
    'Low Conga': 64,
    'Open Conga': 63,
    'Mute Conga': 62,
    'Slap Conga': 63,
};
